runtime: go113
service: slackbot

env_variables:
  SLACK_BOT_CLIENT_ID: '$SLACK_BOT_CLIENT_ID'
  SLACK_BOT_CLIENT_SECRET: '$SLACK_BOT_CLIENT_SECRET'
  SLACK_BOT_SIGNING_SECRET: '$SLACK_BOT_SIGNING_SECRET'
  SLACK_BOT_VERIFICATION_TOKEN: '$SLACK_BOT_VERIFICATION_TOKEN'
  SLACK_BOT_OAUTH_ACCESS_TOKEN: '$SLACK_BOT_OAUTH_ACCESS_TOKEN'
